[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
starclaim_program = "AiU7GFPiL63zRfv1esuWuoHfT6D7K4vJioH5Ci9xTosb"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
